### PR TITLE
Feat/add-missing-test-cases

### PR DESCRIPTION
**Pull request by PavelShkurko**
1.Add Telegram User test cases
2. Adding missing test cases for user_db in progress

### CODE REVIEW

**Comment by PavelShkurko** [comment]
@djeck1432 Please, code review, I will deliver rest tomorrow, sorry for delay

**Comment by PavelShkurko** [comment]
@djeck1432 Please, code review, I've done missing part

**Review by djeck1432 — CHANGES_REQUESTED** [review]
You have duplicated file, please remove from db/crud, it should be only in test/db

**Comment by djeck1432** [comment]
@PavelShkurko please fix pipeline issue

**Review by djeck1432 — APPROVED** [review]
Looks good to me

**Pull request merged**
