### PR TITLE
fixed: fixed all pylint errors

### LINKED ISSUE #88: Fix all pylint issues
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Set up the project, read [README.md](https://github.com/djeck1432/spotnet/blob/main/README.md#development-environment-setup) how to do that.
3. In root folder, run next command: 
```
pylint $(git ls-files '*.py') --disable=all --enable=C0114,C0115,C0116,C0301
```
4. Fix all issues from output of the running `pylint` command
Result of task done -> while creating PR, you won't have any issues in pylint and it will be marked as passed

### PR DESCRIPTION
**Pull request by ikemHood**
Fixes #88 

 - Ran `pylint $(git ls-files '*.py') --disable=all --enable=C0114,C0115,C0116,C0301`
 - Fixed resulting errors outputed

### CODE REVIEW

**Comment by djeck1432** [comment]
Looks good to me, please sync with `main` where I added pylint flow, so we will see here result of your work.
If pipeline will be passed, I will approve and merged it
@ikemHood

**Review by djeck1432 — COMMENTED** [review]
Looks good to me, please sync with main where I added pylint flow, so we will see here result of your work.
If pipeline will be passed, I will approve and merged it
@ikemHood

**Comment by ikemHood** [comment]
It is sync, wonder why the flow is not been triggered

**Comment by ikemHood** [comment]
@djeck1432 I did a little tweak on the workflow and it works, you might have to approve it to run

**Review by djeck1432 — APPROVED** [review]
Looks good to me, approved

**Pull request merged**
