### PR TITLE
add test cases for delete methods

### PR DESCRIPTION
**Pull request by Elsie-ND**
@djeck1432 kindly review changes made to the issue: https://github.com/djeck1432/spotnet/issues/268

### CODE REVIEW

**Comment by djeck1432** [comment]
@Elsie-ND Pipeline is failed, please fix that

**Review by djeck1432 — CHANGES_REQUESTED** [review]
why did you create new files instead of insert those test cases to existing ones?

**Comment by djeck1432** [comment]
@Elsie-ND you will be unassigned if there is no update during next few hours

**Comment by Elsie-ND** [comment]
@djeck1432 I am moving the tests to the existing files and I will be done by today

**Comment by djeck1432** [comment]
@Elsie-ND unassigned, didn't response within 12 hours

**Comment by djeck1432** [comment]
@Elsie-ND it takes 5 mins, do you need for that 5 hours? 
tomorrow morning you will be unassigned

**Comment by djeck1432** [comment]
Screenshot 2024-12-01 at 12 32 15
@Elsie-ND PLease, check it after pushing your changes, fix it

**Comment by djeck1432** [comment]
@Elsie-ND Please, sync with main branch

**Comment by djeck1432** [comment]
@Elsie-ND Please, fix changes, last PR

**Pull request merged**
