### PR TITLE
feat: congratulations modal

### LINKED ISSUE #157: Add new Congratulation page from figma
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Create new page `congratulation` from figma
3. Redirect to this page, once `Postion is opened` 
4. Text me in DM [telegram] to get access to figma djeck_vorobey1

### PR DESCRIPTION
**Pull request by Jemiiah**
fixes #157

### CODE REVIEW

**Review by whateverfw — APPROVED** [review]

**Comment by djeck1432** [comment]
@Jemiiah Please, resolve conflicts

**Comment by Jemiiah** [comment]
done ser @djeck1432

**Review by whateverfw — APPROVED** [review]
Looks good to me @Jemiiah @djeck1432

**Review by djeck1432 — APPROVED** [review]
Looks good to me

**Pull request merged**
