### PR TITLE
feat: position history page

### PR DESCRIPTION
**Pull request by Pvsaint**
position history page

### CODE REVIEW

**Comment by whateverfw** [comment]
@Pvsaint any updates?

**Comment by Pvsaint** [comment]
I've been trying to connect to backend but having difficulties

**Comment by djeck1432** [comment]
@Pvsaint Please, text me in DM @djeck_vorobey1, Please, DON'T hesitate, otherwise you will be unassigned, 15 hours without updates and texting me about any issue, which cause unassigned and closing PR

**Comment by djeck1432** [comment]
Closed, can't reach contributors

**Pull request closed without merging**
