### PR TITLE
Feat: Adding CRM token verification

### PR DESCRIPTION
**Pull request by Villarley**

### CODE REVIEW

**Comment by djeck1432** [comment]
@Villarley please, don't forget to adjust test cases to pass github workflows

**Comment by djeck1432** [comment]
@Villarley Any updates?

**Comment by Villarley** [comment]
> @Villarley Any updates?

Working on it sir!

**Comment by djeck1432** [comment]
@Villarley please, resolve also merge conflict

**Comment by Villarley** [comment]
> @Villarley please, resolve also merge conflict
Hi sir! just finishing the test cases.

**Comment by djeck1432** [comment]
Please, fix test cases @Villarley 
Screenshot 2024-11-17 at 11 25 28

**Comment by djeck1432** [comment]
@Villarley Any updates?

**Comment by Villarley** [comment]
> @Villarley Any updates?

working on it

**Comment by Villarley** [comment]
@djeck1432 ready sir!

**Review by djeck1432 — APPROVED** [review]
Looks good to me

**Pull request merged**
