### PR TITLE
(wip)feat: add notification window

### PR DESCRIPTION
**Pull request by Ibinola**

### CODE REVIEW

**Comment by Ibinola** [comment]
I have access to the `wallet_id` from the `useEffect` on the dashboard page, though it currently returns `undefined`. However, I don’t have access to the `telegram_id`. Could you clarify how I can send the request with these parameters?

image

**Comment by djeck1432** [comment]
@Ibinola Yeah, you are right, we need to adjust pop-up window in case it's not telegram mini-app then user should provide with telegram handler

**Comment by Ibinola** [comment]
okay, but made some changes, please review

**Review by whateverfw — CHANGES_REQUESTED** [review]

**Comment by djeck1432** [comment]
@Ibinola any updates, you will be unassigned for the issue if you not fix your comment in upcoming hours!

**Comment by whateverfw** [comment]
@Ibinola please fix build (see CI)

**Comment by Ibinola** [comment]
yeah on it, just saw it

**Comment by whateverfw** [comment]
@Ibinola can you remove please current bg image? (which is for .notification-wrapper), so modal will look like this:
image

Backgorund in figma was provided as an illustration, but in general modal should be opened and have whatever current page is on a background.

**Comment by Ibinola** [comment]
> @Ibinola can you remove please current bg image? (which is for .notification-wrapper), so modal will look like this: image
> 
> Backgorund in figma was provided as an illustration, but in general modal should be opened and have whatever current page is on a background.

ohhh gotcha!!

**Comment by whateverfw** [comment]
@Ibinolaimage

remove backdrop filter

**Review by whateverfw — APPROVED** [review]
@Ibinola @djeck1432 Looks good to me

**Review by djeck1432 — APPROVED** [review]
Good job, thank you for quick fixes

**Pull request merged**
