### PR TITLE
Refactor/test adjusted to axios instance from axios

### PR DESCRIPTION
**Pull request by OWK50GA**
Went through tests, contract.test.js and transaction.test.js, replacing all the axios calls with axiosInstance calls and eventually removing the backed url (mockBackendUrl) in them.

### CODE REVIEW

**Review by whateverfw — CHANGES_REQUESTED** [review]
Can you make these changes as a single pr? Because it is already 3rd pr, but it actually should be a single one
 
Also build failed, check CI.

Please also resolve merge conflicts

Before you next commit please try to run `npm run build` locally and make sure it works

**Comment by whateverfw** [comment]
@OWK50GA what is the status of this?

**Comment by djeck1432** [comment]
@OWK50GA Please, fix all comments and resolve conflict today

**Comment by OWK50GA** [comment]
> @OWK50GA what is the status of this?

Working on it

**Comment by djeck1432** [comment]
@OWK50GA Tests failed

**Review by whateverfw — APPROVED** [review]

**Comment by whateverfw** [comment]
Approved

**Review by djeck1432 — APPROVED** [review]
Looks good to me

**Pull request merged**
