### PR TITLE
Add logic for saving transaction id

### LINKED ISSUE #348: [Backend] Add logic for saving transaction id
🚨 Attention: Please read the guidelines before applying; otherwise, you will be ignored. 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy

1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Add new model Transaction in this [file](https://github.com/djeck1432/spotnet/blob/main/web_app/db/models.py) with next fields :
- position_id
- status  (opened, closed)
- transaction_hash: str
3. Add crud method to [PositionDBConncetor](https://github.com/djeck1432/spotnet/blob/main/web_app/db/crud/position.py):
- save_transaction(position_id, status, transaction_hash)
4. Add test cases for `save_transaction` method 
5. Don't forget to run generating migration file

### PR DESCRIPTION
**Pull request by raizo07**
closes #348

### CODE REVIEW

**Review by djeck1432 — COMMENTED** [review]
so far looks good

**Review by djeck1432 — CHANGES_REQUESTED** [review]
I can't see migration file, could you please add it

**Comment by raizo07** [comment]
@djeck1432 yeah I'm on it still, will open it up soon.

**Comment by djeck1432** [comment]
@raizo07 any updates? if you need a help let me know

**Comment by raizo07** [comment]
@djeck1432 will add the migration file and open it up for full review

**Review by djeck1432 — APPROVED** [review]
Looks good to me

**Pull request merged**
