### PR TITLE
feat: create test cases for new crud methods

### LINKED ISSUE #268: [Backend] Create test cases for new  crud methods
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Create test cases for these methods in appropriate files in  [`tests`](https://github.com/djeck1432/spotnet/tree/main/web_app/tests/db) folder:
- [`delete_all_users_airdrop`] - https://github.com/djeck1432/spotnet/blob/main/web_app/db/crud.py#L686
- [`delete_all_user_positions `] - https://github.com/djeck1432/spotnet/blob/main/web_app/db/crud.py#L634
- [`delete_object`] -  https://github.com/djeck1432/spotnet/blob/main/web_app/db/crud.py#L117

### PR DESCRIPTION
**Pull request by DotworldX**
resolves #268

### CODE REVIEW

**Comment by djeck1432** [comment]
@DotworldX Please, fix [pylint](https://github.com/djeck1432/spotnet/actions/runs/12021439027/job/33511942372?pr=270) and [test cases](https://github.com/djeck1432/spotnet/actions/runs/12021439027/job/33511942372?pr=270)

**Comment by djeck1432** [comment]
@DotworldX I will unassign you in 4 hours, as I don't have any response and don't see any new commits.

**Comment by DotworldX** [comment]
I will do that now.  sorry about the delay

________________________________

**Comment by DotworldX** [comment]
I unfortunately won't be able to finish up as my laptop needs fixing
urgently. It can't turn on
Feel free to assign the task to someone else. I appreciate the opportunity
and hope sometimes in the future I can be able to work on projects without
laptop failures

**Comment by djeck1432** [comment]
@DotworldX Can't manage task due to computer problems

**Pull request closed without merging**
