### PR TITLE
Added supported wallets to `connect` function

### LINKED ISSUE #146: Disable unused wallets on Frontend
1. Read [guidelines](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5).
2. At the moment, we have a batch of wallets, which we don't want to support:
Screenshot 2024-10-30 at 9 14 33
3. We want to have only `argent X` and `bravos` 
4. Make this changes on Frontend to restrict choices for available wallets. Wallet code is [here](https://github.com/djeck1432/spotnet/blob/main/frontend/src/utils/wallet.js)

### PR DESCRIPTION
**Pull request by SailorJhay**
Fixes #146

### CODE REVIEW

**Comment by SailorJhay** [comment]
Screenshot from 2024-10-30 09-48-33

**Comment by SailorJhay** [comment]
Here @djeck1432 

Please review.

**Review by djeck1432 — APPROVED** [review]
Looks good to me

**Comment by djeck1432** [comment]
Please, fix issues with test cases @SailorJhay

**Comment by djeck1432** [comment]
Screenshot 2024-10-30 at 10 02 08
@SailorJhay It should be green everywhere

**Comment by djeck1432** [comment]
@SailorJhay Any updates?

**Review by djeck1432 — CHANGES_REQUESTED** [review]
Please, fix pipelines

**Comment by djeck1432** [comment]
@SailorJhay Fix please test cases, otherwise you will get partially reward

**Comment by SailorJhay** [comment]
Ok doing that now, sorry didn't see  this.

**Comment by SailorJhay** [comment]
Once again, I am sorry for my responsiveness.

**Review by djeck1432 — COMMENTED** [review]
APproved

**Pull request merged**
