### PR TITLE
test: Create scenario for manual testing

### PR DESCRIPTION
**Pull request by deeseeker**
Documented the process for manual testing

### CODE REVIEW

**Review by djeck1432 — COMMENTED** [review]
great job, keep doing with other scenarios

**Comment by deeseeker** [comment]
Thanks. I have tested all scenarios listed in the task since yesterday. Do you want me to test other sections in the app and create new scenarios?

**Comment by djeck1432** [comment]
@deeseeker yeah, exactly

**Comment by deeseeker** [comment]
Okay, I will check it out.

**Comment by djeck1432** [comment]
@deeseeker Hi, any updates?

**Comment by deeseeker** [comment]
Yes, I will be updating the file today. Thanks for your patience

**Comment by djeck1432** [comment]
@deeseeker any updates?

**Comment by djeck1432** [comment]
@deeseeker okay got it, let's finalize it tomorrow, because we will use this doc for testing before launch.
thanks

**Comment by djeck1432** [comment]
@deeseeker any updates?

**Comment by deeseeker** [comment]
I think we can hold on to that for now till when some of those issues are resolved so we can test again.

**Review by djeck1432 — APPROVED** [review]
Good job, looks good to me

**Pull request merged**
