### PR TITLE
feat: Create Test cases for UserDBConnector

### PR DESCRIPTION
**Pull request by raizo07**

### CODE REVIEW

**Comment by djeck1432** [comment]
@raizo07 Please, fix pylint issues
run this command locally to verify you fixed everything
`pylint $(git ls-files '*.py') --disable=all --enable=C0114,C0115,C0116,C0301`

**Review by djeck1432 — CHANGES_REQUESTED** [review]
Run pylint command and fix all issues
`pylint $(git ls-files '*.py') --disable=all --enable=C0114,C0115,C0116,C0301`

**Comment by raizo07** [comment]
@djeck1432 I'm on it now

**Comment by djeck1432** [comment]
@raizo07 test and pylint were failed, please fix that

**Comment by raizo07** [comment]
@djeck1432 kindly review

**Comment by djeck1432** [comment]
Please, @raizo07 fix test cases
https://github.com/djeck1432/spotnet/actions/runs/11535057031/job/32117401302?pr=119

and before creating PR or push your changes, make sure you have run `pytest` command

**Comment by djeck1432** [comment]
@raizo07 any updates?

**Comment by raizo07** [comment]
> @raizo07 any updates?

On it

**Comment by raizo07** [comment]
@djeck1432 Kindly review

**Comment by djeck1432** [comment]
Screenshot 2024-10-28 at 11 03 52
@raizo07 Please, just click approve and run to see result

**Comment by raizo07** [comment]
@djeck1432 
image

**Review by djeck1432 — CHANGES_REQUESTED** [review]
Looks good to me

**Pull request merged**
