### PR TITLE
Folder Structure and Naming Convention Refactoring

### PR DESCRIPTION
**Pull request by System625**
Changes Made:

1. Standardized naming convention across the project:
   - Folders: lowercase with hyphens
   - Components: PascalCase.jsx
   - CSS files: lowercase.css

2. Reorganized component structure:
   - Flattened `/pages` folder structure
   - Created dedicated folders: `/layout`, `/ui`, `/dashboard`, `/vault`, `/home`
   - Moved related components to their respective folders
   - Renamed components to follow convention (e.g., `Button` → `button`)

Purpose
Improve code organization and maintainability by implementing consistent naming conventions and logical component grouping.

### CODE REVIEW

**Comment by whateverfw** [comment]
@System625 you can do `yarn build` locally and it will be faster to understand wether build fails or no

**Comment by System625** [comment]
@whateverfw It works locally, it has been working locally but the pipeline rejects it with this error:
Module not found: Error: Can't resolve './footer.css' or './header.css' in '/app/src/components/layout/footer'
But I don't get this errors locally because the project works on my PC

**Comment by System625** [comment]
@whateverfw  All the css files are in lowercase eg. footer.css or header.css or home.css, should I change them?

**Comment by System625** [comment]
@whateverfw Apologies for the delay and all, seems I can't fix it and my ETA is almost up
You can unassign me and close the pull request so that someone with better understanding can fix the issue
Hopefully I will be able to fix another issue later on
Thank you

**Comment by whateverfw** [comment]
@System625 It's ok, I didn't face such issues before, but it seems like that's because git is not case sensetive by default, that's why it doesn't track file change name to lower case that we need (e.g. Footer.css -> footer.css).
I just googled and you can do `git config core.ignorecase false` and try to change names to correct ones, it should see you file changes.

**Comment by djeck1432** [comment]
@System625 Any updates?

**Comment by System625** [comment]
@djeck1432 Yes the solution worked
Please review

**Review by whateverfw — APPROVED** [review]
lgtm

**Review by djeck1432 — APPROVED** [review]
Looks good to me

**Pull request merged**
